### ISSUE TITLE
Create an "include" helper

### ISSUE THREAD

**Issue by nspeedzy** [handlebars-lang/handlebars.js#1693]
So, I have seen many templating languages like pug and ejs, they have this `include` keyword/helper, Which allows them to include external files/partials. When i started using handlebars, I noticed there was no `include` helper. It will make coding with handlebars, much easier. Heres an example:

```handlebars
<div class="header">
{{include "header.hbs"}}
</div>

<div class="section">
{{include "section.hbs"}}
</div>

<div class="footer">
{{include "footer.hbs"}}
</div>
```

**Comment by ErisDS** [comment]
What would this do that partials doesn't?

https://handlebarsjs.com/guide/#partials

**Comment by nspeedzy** [comment]
@ErisDS Ok, Let's say we have an `index.hbs` file. It looks like this:
```handlebars
<!DOCTYPE html>
<html>
<body>

<div class="header">
    {{include "header.hbs"}}
</div>

<div class="section">
    {{include "section.hbs"}}
</div>

<div class="footer">
    {{include "footer.hbs"}}
</div>

</body>
</html>
``` 
And a `header.hbs` file:
```handlebars
<h1>Header</h1>
<p>Content goes here</p>
```
And then a `section.hbs` file:
```handlebars
<h3>Section header</h3>
<p>Some paragraph</p>
```
And finally, a `footer.hbs` file:
```
<a href="#">Link 1</a>
<a href="#">Link 2</a>
<a href="#">Link 3</a>
```

Now suppose the `index.hbs` file has too much html code, How do we keep the file size small? (because in production, It is better to have small files)

Answer: The solution is to put them in such files that we call as partial files (Not the partials in handlebars). The `header.hbs`, `section.hbs` and `footer.hbs` files were partial files. With the include statement: We can actually have the contents of that handlebars file included in the `index.hbs` file.
Now that is what the include statement would do that the handlebars partials won't. 

Hope that might have given you an idea as to how the `include` helper would work. If you can't add this feature, It's ok

**Comment by aorinevo** [comment]
@nspeedzy, if I'm understanding this correctly, it sounds like you want to abstract out the manual registration of partials by way of an `include` helper.  I thought along the same line a while ago but but ultimately didn't pursue this - mostly due to time constraints and the following considerations, tradeoffs, and thoughts:
 - namespace collision and alerting
 - adding boilerplate code for registering partials on the fly
 - when an include is invoked, does it become available globally (this happens with partials)?  

Does my understanding align with what you had in mind?  I think it would be neat to be able to register and use partials on the fly.

**Comment by ErisDS** [comment]
is it literally just not having to call registerPartial() that you're asking for?

**Comment by nspeedzy** [comment]
@ErisDS Yes! Like a built-in helper. See, I have tried to create the `include` partial where it includes files but it was so close to being successful. Here is the code:

```javascript
var hbs = require("hbs").handlebars; // I am using the 'hbs' module
var fs = require('fs');

hbs.registerHelper("include", (filename = "") => {
    var content = fs.readFileSync(filename); // Using the 'fs' module of nodejs
    var compiled = hbs.compile(content.toString());
    //
    return compiled();
});
```

**Comment by ErisDS** [comment]
I think this is out of scope for handlebars core, because it depends on how handlebars is being used as to how partials need to work. @aorinevo already listed off a few problems, and these are different in Node & the browser. Also anything in core has to be replicated by other language implementations and again the behaviour could differ.

I think what you're looking for is a wrapper library that suits the environment you're using handlebars in and offers the features you need.

You're using hbs, which is one of many available modules that works with express.

However both https://www.npmjs.com/package/express-handlebars and https://github.com/TryGhost/express-hbs (which I maintain, for transparency) have support for configuring a directory of partials that are loaded automatically.

I'm going to close this, as it's a problem solved outside of core on purpose.

**Comment by nspeedzy** [comment]
@ErisDS Ok then. I agree with what you said. Thanks!
