### ISSUE TITLE
Can't find right context when use #each in #each

### ISSUE THREAD

**Issue by ubourdon** [handlebars-lang/handlebars.js#1761]
Hi,

I use double `#each` context but 2nd one is not a sub property of the first iterated one.
ANd by default second context search in sub property of first context.
But I use named prjected parameter `{{#each pdts as | pdtsItem |}}` and second one don't use this ref.
So 2 choices : 
1) named parameter is useless
2) there is a bug when i have 2 #each

See example below :

https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23each%20pdts%20as%20%7C%20pdtsItem%20%7C%7D%7D%5C%5Cn%5C%5CnTest%5C%5Cn%7B%7B%7BpdtsItem.nom%7D%7D%7D%5C%5Cn%5C%5Cn%7B%7B%23each%20clts%20as%20%7C%20cltsItem%20%7C%7D%7D%5C%5Cn%5C%5Cn%7B%7B%7BcltsItem.nom%7D%7D%7D%5C%5CnBlob%7B%7B%2Feach%7D%7D%7B%7B%2Feach%7D%7D%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20pdts%3A%20%5B%7Bnom%3A%20%5C%22TOTO%5C%22%7D%5D%5Cn%20%20%2C%20clts%3A%20%5B%7Bnom%3A%20%5C%22TITI%5C%22%7D%5D%5Cn%20%20%5Cn%7D%5Cn%22%2C%22output%22%3A%22%5C%5Cn%5C%5CnTest%5C%5CnTOTO%5C%5Cn%5C%5Cn%5Cn%22%2C%22preparationScript%22%3A%22%2F%2F%20Handlebars.registerHelper('loud'%2C%20function(string)%20%7B%5Cn%2F%2F%20%20%20%20return%20string.toUpperCase()%5Cn%2F%2F%20%7D)%3B%5Cn%22%2C%22handlebarsVersion%22%3A%224.7.7%22%7D

**Comment by wadouk** [comment]
Workaround

```js

Handlebars.registerHelper("foreach", function(context, options) {
    return context.map((item, i) => {
        let newOptions = {
            data: context,
            blockParams: [context[i], i]
        }
        return options.fn({...context[i], ...options.data.root}, newOptions)
    })
});
```

**Comment by jaylinski** [comment]
An `each`-helper with a named parameter still creates a new context.

The named parameter only helps you with writing `nameParameter.property` instead of `this.property` or when nesting `each`-blocks and referring to the value in the current loop.

You have to use the parent context like this when using a nested each with root-data:
https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23each%20pdts%20as%20%7C%20pdtsItem%20%7C%7D%7D%5C%5Cn%5C%5CnTest%5C%5Cn%7B%7B%7BpdtsItem.nom%7D%7D%7D%5C%5Cn%5C%5Cn%7B%7B%23each%20..%2Fclts%20as%20%7C%20cltsItem%20%7C%7D%7D%5C%5Cn%5C%5Cn%7B%7B%7BcltsItem.nom%7D%7D%7D%5C%5CnBlob%7B%7B%2Feach%7D%7D%7B%7B%2Feach%7D%7D%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20pdts%3A%20%5B%7Bnom%3A%20%5C%22TOTO%5C%22%7D%5D%2C%5Cn%20%20clts%3A%20%5B%7Bnom%3A%20%5C%22TITI%5C%22%7D%5D%5Cn%7D%5Cn%22%2C%22output%22%3A%22%5C%5Cn%5C%5CnTest%5C%5CnTOTO%5C%5Cn%5C%5Cn%5C%5Cn%5C%5CnTITI%5C%5CnBlob%5Cn%22%2C%22preparationScript%22%3A%22%22%2C%22handlebarsVersion%22%3A%224.7.7%22%7D
