### ISSUE TITLE
Support for eval-less template execution

### ISSUE THREAD

**Issue by legrego** [handlebars-lang/handlebars.js#1934]
One of the ways [Kibana](https://github.com/elastic/kibana) leverages Handlebars is via user-supplied templates, which are then executed in the browser.

We recently, _finally_, removed `script-src 'unsafe-eval'` from our Content Security Policy. The most challenging part of this exercise was finding a way to get Handlebars to execute templates without the need for dynamic code generation (in other words, without `eval`).

Inspired by [@nknapp's comment](https://github.com/handlebars-lang/handlebars.js/issues/1443#issuecomment-591072032) in #1443, we took a stab at executing templates by walking the Handlebars-generated AST. We've had our implementation running in production for a little while now, and it's working well for us.

I won't go into too many details about our approach here, but I'll instead refer you to our implementation, which includes a descriptive README:
https://github.com/elastic/kibana/tree/main/packages/kbn-handlebars

If there is a community interest for this, we would be happy to contribute our work to the Handlebars project. Our approach would live alongside the existing approach, rather than replace it. The performance tradeoff would not be acceptable for all users.

So, with all that said:
1) Is there interest in having Handlebars natively support `eval`-less execution?
2) If so, what would be the best way to incorporate our work into the project? What sort of API would you like to see?

----

_aside: I am just the person asking the questions, credit for this work goes to @watson and @thomheymann_

**Comment by salmin89** [comment]
> 1. Is there interest in having Handlebars natively support `eval`-less execution?
> 2. If so, what would be the best way to incorporate our work into the project? What sort of API would you like to see?
> 
> _aside: I am just the person asking the questions, credit for this work goes to @watson and @thomheymann_

1. Yes, we use handlebars and have hit a roadblock due to the origin of this issue. Your fix might be just what we need. Will test it out this week. 
2. I’m not sure if you want to maintain a fork or what the best approach is. I’ll let other people decide on this but I did want to raise appreciation for the solution provided.

**Comment by legrego** [comment]
Thanks for expressing your interest, @salmin89, and do let me know how you make out with your test!

**Comment by salmin89** [comment]
@legrego your solution worked perfectly. I will copy the package for now, but I'd love to see it natively supported by handlebars.

If you don't get any response, are there any plans on publishing your package as a standalone solution?

**Comment by davidfant** [comment]
For those looking, I created a kibana fork to publish `kbn-handlebars`: https://www.npmjs.com/package/kbn-handlebars
https://github.com/davidfant/kibana-handlebars/commit/e3e925c9ee5b4d7f3a8cc60e3b7c202841490490

**Comment by spandl** [comment]
This is great and working for many cases.

I came across a use case that isn't supported: nested expressions.

Example, the first block is working, but the second block isn't omitting the nested *CUSTOM_HELPER* 
```
{{#if (CUSTOM_HELPER "parameter")}}
        Text
{{else}}
         Alternative text
{{/if}}
```

```
{{#if (CUSTOM_HELPER "parameter")}}
        Text with {{CUSTOM_HELPER_2 "parameter"}}
{{else}}
         Alternative text
{{/if}}
```

Chances this could make it into the library?
Thanks!

**Comment by Georift** [comment]
Cheers for the library, and sharing the work with the open source community, so great to have a path forward on this while handlebars upstream is blocked.

Just out of interest I wonder if another solution to this probably could be shipping the `unsafe-eval` work into a worker. And posting messages to and from to do the rendering work. Broadly following something like [this gist describes](https://gist.github.com/dfkaye/da49b6c05aed48e6dfb28a2c7e87cf06)

@legrego @nknapp am I missing something here? Would this not actually solve the issue for some reason or another?

**Comment by nknapp** [comment]
i forgot to mention that i started a project. https://handlebars-ng.knappi.org 

its a bit stale now, but  I would invite everybody who wants to contribute

**Comment by nknapp** [comment]
⁵

> Cheers for the library, and sharing the work with the open source community, so great to have a path forward on this while handlebars upstream is blocked.
> 
> Just out of interest I wonder if another solution to this probably could be shipping the `unsafe-eval` work into a worker. And posting messages to and from to do the rendering work. Broadly following something like [this gist describes](https://gist.github.com/dfkaye/da49b6c05aed48e6dfb28a2c7e87cf06)
> 
> @legrego @thomheymann @watson am I missing something that you might have found in the trenches? Would this not actually solve the issue for some reason or another?

The documentation at handlebars.js uses workers to run templates in the playground. I did this to prevent the main thread from being stuck in endless loops.

**Comment by TotalTechGeek** [comment]
A small update, I've been working on improving compatibility with the mainline project, 

Some of the missing prior features:
- Whitespace Control
- Partial Syntax
- Implicit Iterator and If Support `{{#kids}}...{{/kids}}`
- BlockParams (`as |num|` syntax)
- A handful of alternative ways to reference variables `./` vs `this.` and `{{^}}` instead of `{{else}}`
- Recursive Lookup Support / Enabling & Disabling Escaping
- Some of the stuff Handlebars has matured to support, like iterating over Sets and Maps.

The additions nearly doubled my SLoC count 😅. 

The bench suite needs some more additions, but I'd estimate the overall compatibility to truly be a lot closer to 95-97%, with most use cases being a fairly drop-in substitution. Fortunately the performance seems to have ended up in about the same place where it started.

```
Handlebars Simple: 2203.67ms | 1.00x
Elastic Simple: 1454.22ms | 1.52x
JLE Interpreted Simple: 80.78ms | 27.28x
JLE Async Simple: 91.65ms | 24.04x
JLE Simple: 3.64ms | 605.62x
---
Handlebars SimpleEach: 2400.94ms | 1.00x
Elastic SimpleEach: 3537.01ms | 0.68x
JLE Interpreted SimpleEach: 432.64ms | 5.55x
JLE Async SimpleEach: 159.89ms | 15.02x
JLE SimpleEach: 76.91ms | 31.22x
---
Handlebars SimpleIf: 2257.92ms | 1.00x
Elastic SimpleIf: 1543.33ms | 1.46x
JLE Interpreted SimpleIf: 182.51ms | 12.37x
JLE Async SimpleIf: 75.44ms | 29.93x
JLE SimpleIf: 14.38ms | 157.03x
---
Handlebars SimpleIf (False): 2267.63ms | 1.00x
Elastic SimpleIf (False): 1554.01ms | 1.46x
JLE Interpreted SimpleIf (False): 183.25ms | 12.37x
JLE Async SimpleIf (False): 76.76ms | 29.54x
JLE SimpleIf (False): 17.89ms | 126.76x
---
Handlebars NestedIf: 2278.28ms | 1.00x
Elastic NestedIf: 1555.28ms | 1.46x
JLE Interpreted NestedIf: 198.17ms | 11.50x
JLE Async NestedIf: 72.06ms | 31.62x
JLE NestedIf: 17.41ms | 130.89x
---
Handlebars NestedIf (False): 2670.69ms | 1.00x
Elastic NestedIf (False): 2515.64ms | 1.06x
JLE Interpreted NestedIf (False): 283.52ms | 9.42x
JLE Async NestedIf (False): 84.36ms | 31.66x
JLE NestedIf (False): 19.69ms | 135.63x
---
Handlebars NestedIf (18): 2284.74ms | 1.00x
Elastic NestedIf (18): 1548.73ms | 1.48x
JLE Interpreted NestedIf (18): 182.23ms | 12.54x
JLE Async NestedIf (18): 77.30ms | 29.56x
JLE NestedIf (18): 17.52ms | 130.40x
---
Handlebars EachStatic: 2708.79ms | 1.00x
Elastic EachStatic: 5529.97ms | 0.49x
JLE Interpreted EachStatic: 31.62ms | 85.66x
JLE Async EachStatic: 70.96ms | 38.17x
JLE EachStatic: 13.54ms | 200.05x
---
Handlebars AddExampleWithTraversal: 4107.33ms | 1.00x
Elastic AddExampleWithTraversal: 6588.83ms | 0.62x
JLE Interpreted AddExampleWithTraversal: 1056.67ms | 3.89x
JLE Async AddExampleWithTraversal: 482.76ms | 8.51x
JLE AddExampleWithTraversal: 424.28ms | 9.68x
---
Handlebars Example 1: 3496.99ms | 1.00x
Elastic Example 1: 13478.98ms | 0.26x
JLE Interpreted Example 1: 1738.79ms | 2.01x
JLE Async Example 1: 294.65ms | 11.87x
JLE Example 1: 231.39ms | 15.11x
---
Handlebars YAML: 7409.85ms | 1.00x
Elastic YAML: 21396.63ms | 0.35x
JLE Interpreted YAML: 3168.22ms | 2.34x
JLE Async YAML: 388.12ms | 19.09x
JLE YAML: 326.41ms | 22.70x
---
Handlebars Partials: 5241.32ms | 1.00x
Elastic Partials: 23968.83ms | 0.22x
JLE Interpreted Partials: 655.47ms | 8.00x
JLE Async Partials: 116.11ms | 45.14x
JLE Partials: 56.31ms | 93.07x
```

Some current drawbacks / notable issues:
- The engine's truthiness is configurable; right now, the default is set to JLE's default, which is JavaScript's defaults for truthiness, I'll probably override this soon.
- No support for deprecated features, like decorators or `this/syntax/for/paths`. Inline is just a block helper. 
- Creating new block helpers is undocumented.
- "SafeString" is not a thing for returning from helpers, the behavior is inverted where it expects you to escape if needed. If this ends up being an issue, I may provide an alternative way to register the helpers.
- I have a heck ton of built-in helpers, which opinionates HBS a bit. (A bunch of arithmetic and comparison and string manipulation stuff). 
- No Raw Blocks (I don't fully understand their use case; is the point to be able to make it easier to embed handlebars as text?)

But I think I'm about ready to start gathering templates and aiming for more rigorous compatibility.
